/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicAgentTasksRouteImport } from './routes/api/public/agent/tasks'
import { Route as ApiPublicHooksPollOrdersRouteImport } from './routes/api/public/hooks/poll-orders'
import { Route as ApiPublicSmsWebhookRouteImport } from './routes/api/public/sms/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTasksRoute = ApiPublicAgentTasksRouteImport.update({
  id: '/api/public/agent/tasks',
  path: '/api/public/agent/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPollOrdersRoute =
  ApiPublicHooksPollOrdersRouteImport.update({
    id: '/api/public/hooks/poll-orders',
    path: '/api/public/hooks/poll-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmsWebhookRoute = ApiPublicSmsWebhookRouteImport.update({
  id: '/api/public/sms/webhook',
  path: '/api/public/sms/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/agent/tasks': typeof ApiPublicAgentTasksRoute
  '/api/public/hooks/poll-orders': typeof ApiPublicHooksPollOrdersRoute
  '/api/public/sms/webhook': typeof ApiPublicSmsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/agent/tasks': typeof ApiPublicAgentTasksRoute
  '/api/public/hooks/poll-orders': typeof ApiPublicHooksPollOrdersRoute
  '/api/public/sms/webhook': typeof ApiPublicSmsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/agent/tasks': typeof ApiPublicAgentTasksRoute
  '/api/public/hooks/poll-orders': typeof ApiPublicHooksPollOrdersRoute
  '/api/public/sms/webhook': typeof ApiPublicSmsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/agent/tasks'
    | '/api/public/hooks/poll-orders'
    | '/api/public/sms/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/public/agent/tasks'
    | '/api/public/hooks/poll-orders'
    | '/api/public/sms/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/agent/tasks'
    | '/api/public/hooks/poll-orders'
    | '/api/public/sms/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicAgentTasksRoute: typeof ApiPublicAgentTasksRoute
  ApiPublicHooksPollOrdersRoute: typeof ApiPublicHooksPollOrdersRoute
  ApiPublicSmsWebhookRoute: typeof ApiPublicSmsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/tasks': {
      id: '/api/public/agent/tasks'
      path: '/api/public/agent/tasks'
      fullPath: '/api/public/agent/tasks'
      preLoaderRoute: typeof ApiPublicAgentTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/poll-orders': {
      id: '/api/public/hooks/poll-orders'
      path: '/api/public/hooks/poll-orders'
      fullPath: '/api/public/hooks/poll-orders'
      preLoaderRoute: typeof ApiPublicHooksPollOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/webhook': {
      id: '/api/public/sms/webhook'
      path: '/api/public/sms/webhook'
      fullPath: '/api/public/sms/webhook'
      preLoaderRoute: typeof ApiPublicSmsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicAgentTasksRoute: ApiPublicAgentTasksRoute,
  ApiPublicHooksPollOrdersRoute: ApiPublicHooksPollOrdersRoute,
  ApiPublicSmsWebhookRoute: ApiPublicSmsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
